<a href="https://colab.research.google.com/github/Kinley-afk/AI-Foundation-Training-Assignments/blob/main/Numpy_2D_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider the following list a, convert it to Numpy Array.

In [1]:
# Write your code below and press Shift+Enter to execute
import numpy as np
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

arr = np.array(a)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Calculate the numpy array size.

In [3]:
# Write your code below and press Shift+Enter to execute
arr.size

12

Access the element on the first row and first and second columns.

In [4]:
# Write your code below and press Shift+Enter to execute
arr[0][0:2]

array([1, 2])

Perform matrix multiplication with the numpy arrays A and B.

In [5]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
res = np.dot(arr, B)
res

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])